import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const projectRoot = process.cwd();
const docsRoot = path.join(projectRoot, "content", "docs");
const failures = [];

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const absolute = path.join(directory, entry.name);
      return entry.isDirectory() ? walk(absolute) : [absolute];
    }),
  );

  return files.flat();
}

function routeForFile(file) {
  const relative = path.relative(docsRoot, file).replaceAll(path.sep, "/");
  const withoutExtension = relative.replace(/\.mdx$/, "");

  if (withoutExtension === "index") return "/";
  if (withoutExtension.endsWith("/index")) {
    return `/${withoutExtension.slice(0, -"/index".length)}`;
  }

  return `/${withoutExtension}`;
}

function removeFrontmatter(markdown) {
  return markdown.replace(/^---\n[\s\S]*?\n---\n?/, "");
}

function slugifyHeading(value) {
  return value
    .toLowerCase()
    .replace(/<[^>]+>/g, "")
    .replace(/[`*_~]/g, "")
    .replace(/[^\p{Letter}\p{Number}\s-]/gu, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

function collectAnchors(markdown) {
  const anchors = new Set();
  const counts = new Map();

  for (const match of removeFrontmatter(markdown).matchAll(/^#{2,6}\s+(.+)$/gm)) {
    const base = slugifyHeading(match[1]);
    const count = counts.get(base) ?? 0;
    counts.set(base, count + 1);
    anchors.add(count === 0 ? base : `${base}-${count}`);
  }

  return anchors;
}

function readFrontmatterValue(markdown, key) {
  const frontmatter = markdown.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? "";
  return frontmatter.match(new RegExp(`^${key}:\\s*(.+)$`, "m"))?.[1]?.trim();
}

const allFiles = await walk(docsRoot);
const mdxFiles = allFiles.filter((file) => file.endsWith(".mdx"));
const pages = await Promise.all(
  mdxFiles.map(async (file) => {
    const markdown = await readFile(file, "utf8");
    return {
      file,
      markdown,
      route: routeForFile(file),
      anchors: collectAnchors(markdown),
      title: readFrontmatterValue(markdown, "title"),
      description: readFrontmatterValue(markdown, "description"),
    };
  }),
);

const routes = new Map();
const titles = new Map();

for (const page of pages) {
  const other = routes.get(page.route);
  if (other) {
    failures.push(
      `${path.relative(projectRoot, page.file)}: duplicate route ${page.route} also generated by ${path.relative(projectRoot, other.file)}`,
    );
  } else {
    routes.set(page.route, page);
  }
}

const legacyRedirects = JSON.parse(
  await readFile(path.join(projectRoot, "legacy-redirects.json"), "utf8"),
);
for (const [source, destination] of Object.entries(legacyRedirects)) {
  if (!source.startsWith("/") || !destination.startsWith("/")) {
    failures.push(`legacy-redirects.json: non-local migration ${source} → ${destination}`);
  }
  if (routes.has(source)) {
    failures.push(`legacy-redirects.json: redirects a published page ${source}`);
  }
  if (!routes.has(destination)) {
    failures.push(`legacy-redirects.json: ${source} targets missing page ${destination}`);
  }
  if (source === destination || Object.hasOwn(legacyRedirects, destination)) {
    failures.push(`legacy-redirects.json: chain or loop ${source} → ${destination}`);
  }
}

for (const page of pages) {
  const label = path.relative(projectRoot, page.file);

  if (!page.title) failures.push(`${label}: missing frontmatter title`);
  if (!page.description) failures.push(`${label}: missing frontmatter description`);

  if (page.title) {
    const other = titles.get(page.title);
    if (other) failures.push(`${label}: duplicate title also used by ${other}`);
    titles.set(page.title, label);
  }

  const targets = [
    ...Array.from(
      page.markdown.matchAll(
        /\[[^\]]+\]\((\/[^)\s]+)(?:\s+"[^"]*")?\)/g,
      ),
      (match) => match[1],
    ),
    ...Array.from(
      page.markdown.matchAll(/\bhref\s*=\s*["'](\/[^"']+)["']/g),
      (match) => match[1],
    ),
  ];

  for (const target of targets) {
    if (target.startsWith("//")) continue;
    const [targetRoute, targetAnchor] = target.split("#", 2);
    const targetPage = routes.get(targetRoute || "/");

    if (!targetPage) {
      failures.push(`${label}: internal link points to missing route ${target}`);
      continue;
    }

    if (targetAnchor && !targetPage.anchors.has(targetAnchor)) {
      failures.push(`${label}: internal link points to missing anchor ${target}`);
    }
  }
}

for (const metaFile of allFiles.filter((file) => file.endsWith("meta.json"))) {
  const meta = JSON.parse(await readFile(metaFile, "utf8"));
  const directory = path.dirname(metaFile);
  const label = path.relative(projectRoot, metaFile);

  for (const entry of meta.pages ?? []) {
    const candidateMdx = path.join(directory, `${entry}.mdx`);
    const candidateIndex = path.join(directory, entry, "index.mdx");
    if (!mdxFiles.includes(candidateMdx) && !mdxFiles.includes(candidateIndex)) {
      failures.push(`${label}: pages entry "${entry}" has no MDX page`);
    }
  }
}

const rootPage = routes.get("/");
if (rootPage && /^#{2,6}\s+/m.test(removeFrontmatter(rootPage.markdown))) {
  failures.push(
    "content/docs/index.mdx: contains headings that are indexed but not rendered by the custom homepage",
  );
}

const packageJson = JSON.parse(
  await readFile(path.join(projectRoot, "package.json"), "utf8"),
);
for (const [name, version] of Object.entries(packageJson.dependencies ?? {})) {
  if (version === "latest") failures.push(`package.json: ${name} is not pinned`);
}

const sourceFiles = allFiles.filter(
  (file) => file.endsWith(".mdx") || file.endsWith(".json"),
);
const codeFiles = (await walk(path.join(projectRoot, "src"))).filter(
  (file) => /\.(?:ts|tsx|js|mjs)$/.test(file),
);
const projectDocs = [path.join(projectRoot, "README.md")];
for (const file of codeFiles) {
  const contents = await readFile(file, "utf8");
  for (const match of contents.matchAll(/\bhref\s*=\s*["'](\/[^"']+)["']/g)) {
    const target = match[1];
    const route = target.split(/[?#]/, 1)[0];
    if (route.startsWith("//")) continue;
    if (!routes.has(route)) {
      failures.push(`${path.relative(projectRoot, file)}: UI link targets missing page ${target}`);
    }
  }
}
for (const file of [...sourceFiles, ...codeFiles, ...projectDocs]) {
  const contents = await readFile(file, "utf8");
  if (contents.includes("docs.halema.com")) {
    failures.push(
      `${path.relative(projectRoot, file)}: references the parked docs.halema.com domain`,
    );
  }
}

if (failures.length > 0) {
  console.error(`Documentation integrity check failed (${failures.length}):`);
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log(
  `Documentation integrity check passed: ${pages.length} pages, ${routes.size} routes, ${Object.keys(legacyRedirects).length} permanent redirects.`,
);
